### ISSUE TITLE
Hud bar position

### ISSUE THREAD

**Issue by z3r0m1nd** [thers/FRFuel#10]
![20170630-jug66](https://user-images.githubusercontent.com/10498486/27716448-22e3a3a0-5d47-11e7-8bb0-a37814204751.png)

**Comment by z3r0m1nd** [comment]
also, can you provide nativeui.net link?

**Comment by thers** [comment]
You can build NativeUI by yourself: https://github.com/citizenfx/NativeUI

**Comment by thers** [comment]
Fixed in https://github.com/thers/FRFuel/pull/12
