### ISSUE TITLE
Unable to use built DLL

### ISSUE THREAD

**Issue by amerine** [thers/FRFuel#2]
Hey @RiderSx,

First, thanks for sharing your code! I didn't realize we could even use C# until you posted the to teh forums. 

I'm having issues using a DLL I've built locally. The GTA V client, when connecting to the server fires off a `not calling parent constructor .ctor()` error (Sorry for not having the exact error message, I'm on another machine at the moment). 

Would it be possible for you to elaborate a bit more in the README with info on how you've setup VS to work? Where did you get the `nativeui.net.dll` dll? 

Thanks again for this. <3

--mark

**Comment by amerine** [comment]
And to be specific, the error is only visible in the F8 log in-game. No exceptions are thrown. I am able to use your released frfuel dll without issue, just not my own build.

**Comment by RiderSx** [comment]
Oh, sure thing, i'll add some bitsin README. But for now you can take a look into [this](https://github.com/RiderSx/fr-docs/blob/master/Guides/CSharpScriptingEnvironmentSetup.md).

**Comment by Povers** [comment]
Hi,
Can you add .sln to your repo ? We can't build DLL actually.
Thanks

**Comment by thers** [comment]
@Povers sure thing, added `.sln`.

**Comment by Povers** [comment]
Thanks for your work 😃

**Comment by Esquimen** [comment]
Hello, good job for tuto !
I have a problem, When I compile via visual studio a cs in library of class it crash. What is the solution ?
