### ISSUE TITLE
Allow control from other resources

### ISSUE THREAD

**Issue by justweb1** [thers/FRFuel#21]
I apologize if this is not the place for feature requests.

I would like to see a couple additional events that would allow access from other custom scripts. I am writing a roadside assistance script and we use frfuel. I would like to have an AI Ped drive out to the player and fill their vehicle with fuel if they ran out. Please let me know if you need some additional information.

frfuel:currentfuel -> (amount: float) - Checks current fuel level.
frfuel:addfuel -> (amount: float) - Allows adding fuel.

**Comment by thers** [comment]
Hi, thanks for the suggestion. I think it will be a unnecessary sophisticated to use events for such.

There's a better alternative of using exports thing. So the usage will be like so (js):
```js
exports.frfuel.getCurrentFuelLevel(); // 31.12345

exports.frfuel.addFuel(amount); // will return final fuel level
```

**Comment by justweb1** [comment]
Would this work the same way for LUA as well then? I haven't played with exports too much yet.

**Comment by thers** [comment]
Yes, it will, usage is pretty similar:
```lua
exports.frfuel:getCurrentFuelLevel();
```

**Comment by justweb1** [comment]
@thers 
I am not familiar with .cs otherwise I would submit a merge request and I hate to ask, but I am looking for this to add this to my script. Do you have an idea of when it might be added?

**Comment by thers** [comment]
Hey @justweb1 sorry for the delay. I am really busy rn and can't implement these things atm. But you can expect them to be implemented during next week, they'll be pushed in version `1.2.0`.

**Comment by justweb1** [comment]
@there That's great.

**Comment by thers** [comment]
Fixed in https://github.com/thers/FRFuel/commit/fcbdf202a0539e90f28f0d4916c82dbb85dd397c

**Comment by thers** [comment]
@justweb1 checkout original post on fivem forums for details.

**Comment by justweb1** [comment]
@thers Works Great! Great Job.
