### ISSUE TITLE
Comet5 Fuel Consumption (Maybe others)

### ISSUE THREAD

**Issue by rdephillip** [thers/FRFuel#29]
Comet5 Fuel consumption is insanely high!  The Comet2 is more reasonable but for some reason the Comet5 appears to consume 1% per Tick even when idling and it acts like it has a 1 liter tank.

I would imagine that even with the calculations the tank size of the two vehicles would be similar.  The Comet5 actually appears to be a less powerful vehicle than the Comet2 which makes this more confusing.

**Comment by TomGrobbe** [comment]
Most likely the comet5 has a very small fuel tank. This can be changed in the vehicles.meta. Thers and myself are planning on creating a system where you can manually override tank capacity per vehicle using some sort of config file. But this still needs more planning and actually implementing it will take even longer as we're both quite busy atm.
