### ISSUE TITLE
Manual refuel seems to not trigger event "addedFuel"

### ISSUE THREAD

**Issue by bt0r** [thers/FRFuel#6]
Hello mate,

When using AddEventHandler("frfuel:addedFuel") , it works in a vehicle but it doesnt work with manual refuel (with petrol can).
Can you confirm and if it's possible, fix it ? 

Thanks a lot for your work !

**Comment by thers** [comment]
And it shouldn't as `frfuel:addedFuel` was made for money systems.

**Comment by bt0r** [comment]
Okay but if frfuel:addedFuel is made for money system, why do you not use it with manual refuel (with petrol can) ? Actually, people can refuel using both but the event is not triggered in manual refuel

**Comment by thers** [comment]
Because it makes no sense to charge for what you already have :) And since `v1.0.0` you can disable Jerry Cans from spawning and sell them on your own.

**Comment by bt0r** [comment]
Ok ok, i didn't know that we can disable jerry can. This is a good point.

Thanks for your answers
