### ISSUE TITLE
Errors FRFuel.cs compiling

### ISSUE THREAD

**Issue by Aleweadan** [thers/FRFuel#8]
I have many error on compiling with Visual Studio Pro 2015:

Erreur	CS1043	{ ou ; attendu	FRFuel.cs	51	Actif
Erreur	CS1513	} attendue	 FRFuel.cs	51	Actif
Erreur	CS0161	'FRFuel.LastVehicle.get' : les chemins de code ne retournent pas tous une valeur FRFuel.cs	51	Actif

Line 51 : protected Vehicle LastVehicle { get => lastVehicle; set => lastVehicle = value; }

**Comment by thers** [comment]
You need VS 2017.
